# Generated by Django 5.0.6 on 2024-06-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="s_id",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="history",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
