# Generated by Django 5.0.6 on 2024-06-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0005_history_s_id_alter_history_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
