# Generated by Django 5.0.6 on 2024-06-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0006_alter_history_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="QaList",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=20)),
                ("qa", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "QA_LIST",
                "managed": False,
            },
        ),
    ]
