# Generated by Django 5.0.6 on 2024-06-13 01:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0007_qalist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QaList",
        ),
    ]
